version: '3.9'

services:
  mongodb:
      image: mongo:latest
      container_name: mongodb
      restart: always
      volumes:
        - ./mongodb:/data/db
      networks:
        - datanet
  backend:
    depends_on:
      - mongodb
    image: xavierhenriquec/modtrust:latest
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
    networks:
      - datanet

  frontend-build:
    image: node
    working_dir: /app
    volumes:
      - ./Interface:/app
    command: ["sh", "-c", "npm install && npm run build"]
    depends_on:
      - backend
    networks:
      - datanet

  nginx:
    image: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./Interface/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - backend
      - frontend-build
    networks:
      - datanet

networks:
  datanet:
    driver: bridge