version: '3.9'

services:
  backend:
    depends_on:
      - mongodb
    image: xavierhenriquec/modtrust:latest
    container_name: backend
    ports:
      - "3000:3000"
      - "8080:8080"
    restart: always
    networks:
      - datanet

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - ./mongodb:/data/db
    networks:
      - datanet
networks:
  datanet:
    driver: bridge
