version: '3.8'

services:
  server:
    depends_on:
      - mongo
    image: xavierhenriquec/modtrust:latest
    privileged: true
    platform: linux/arm64/v8
    container_name: server
    ports:
      - "3000:3000"
      - "8080:8080"
    restart: always
    networks:
      - datanet

  mongo:
    image: arm64v8/mongo:latest
    platform: linux/arm64/v8
    container_name: mongo
    privileged: true
    restart: always
    volumes:
      - ./mongodb:/data/db
    networks:
      - datanet
networks:
  datanet:
    driver: bridge
