version: '3.9'

services:
  server:
    depends_on:
      - mongo
    image: xavierhenriquec/modtrust:latest
    container_name: server
    privileged: true
    ports:
      - "3000:3000"
      - "8080:8080"
    restart: always
    networks:
      - datanet

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - ./mongodb:/data/db
    networks:
      - datanet
networks:
  datanet:
    driver: bridge
